Feature/ubi 246 gke deployment
Ubivius/telemetry-grafana pull request #1
Opened 2021-02-21 19:08 UTC by MaximeStOnge

#### What changes does this PR contain?
- Resources override 
- Readme
- Enable persistence
- Define the service's type as LoadBalancer to expose Grafana externally
- Add datasources 

#### Which JIRA ticket ID's are associated with this PR?
UbI-246

#### Additional comments and information

2021-02-21 20:36 UTC, ysma500 requested changes

2021-02-21 20:36 UTC, ysma500 commented on chart/values.yaml
> +  limits:
Req first

2021-02-21 23:07 UTC, ysma500 approved these changes

2021-02-22 23:12 UTC, ArcticWalrus approved these changes

2021-02-22 23:12 UTC, merged